// 071-now overlay builder (Issue #108 feasibility spike).
//
//     The browser-based blog runs an in-php-wasm copy of WordPress 0.71.
//     That copy is built here: src/ is snapshotted into tools/playground/wp/,
//     then the 071-now SQLite database shim is overlaid on top.
//
//     src/ itself is NEVER modified -- per Issue #108, the real
//     WordPress 0.71 source and its MySQL / Docker setup must keep
//     working. The overlay only changes tools/playground/wp/, a generated,
//     git-ignored directory that exists solely for the in-browser copy.
//
//     The overlay is a single file: b2-include/wp-db.php is replaced by
//     tools/playground/db/wp-db.php, the SQLite-backed reimplementation.
//     The boot prepend (tools/playground/db/seed.php) is also copied in so
//     the php-wasm boot shim can run it.
import {
	cpSync,
	rmSync,
	mkdirSync,
	copyFileSync,
	writeFileSync,
	readFileSync,
	existsSync,
} from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

// This file is tools/playground/scripts/build-overlay.mjs, so the
//     playground package is one level up and the repo root is three.
const here = dirname( fileURLToPath( import.meta.url ) );
const playgroundDir = join( here, '..' );
const repoRoot = join( playgroundDir, '..', '..' );

const srcDir = join( repoRoot, 'src' );
const toolsDir = join( repoRoot, 'tools' );
const wpDir = join( playgroundDir, 'wp' );
const dbDir = join( playgroundDir, 'db' );

if ( ! existsSync( srcDir ) ) {
	console.error( `[071-now] source not found: ${ srcDir }` );
	process.exit( 1 );
}

// Build the block-editor app so its bundle lands in the overlay.
//
//     The block editor is a custom @wordpress/block-editor app over a
//     thin WordPress 0.71 JSON backend. Its React app, tools/
//     block-editor/, is a self-contained package with its own
//     package.json and package-lock.json -- deliberately not a
//     repo-root workspace -- and `npm run build` there writes the
//     bundle and the Vite manifest to src/block-editor/assets/, a
//     git-ignored build artifact. src/block-editor/api/editor.php reads
//     that manifest to serve the editor; without the bundle it shows a
//     "Block editor bundle not built" fallback.
//
//     The playground overlay is a snapshot of src/, so the block editor
//     works in the playground only if src/block-editor/assets/ exists
//     when the snapshot is taken. This builds the app here, before the
//     snapshot below, so the overlay always carries a fresh bundle. The
//     build writes only into src/block-editor/assets/ (git-ignored); src/
//     itself is otherwise untouched, exactly as the overlay contract
//     requires.
const blockEditorAppDir = join( toolsDir, 'block-editor' );
const blockEditorAssetsDir = join( srcDir, 'block-editor', 'assets' );

/**
 * Run a command in a directory, inheriting stdio, and exit the build
 *     on failure.
 * @param {string}   command The executable to run.
 * @param {string[]} args    Its arguments.
 * @param {string}   cwd     The working directory.
 * @param {string}   label   A human-readable label for the error message.
 */
function run( command, args, cwd, label ) {
	const result = spawnSync( command, args, {
		cwd,
		stdio: 'inherit',
		// npm is a .cmd shim on Windows; a shell run resolves it.
		shell: process.platform === 'win32',
	} );
	if ( result.status !== 0 ) {
		console.error( `[071-now] ${ label } failed` );
		process.exit( 1 );
	}
}

if ( ! existsSync( join( blockEditorAppDir, 'node_modules' ) ) ) {
	console.log( '[071-now] installing block-editor app dependencies…' );
	run( 'npm', [ 'install' ], blockEditorAppDir, 'block-editor npm install' );
}

console.log( '[071-now] building the block-editor app…' );
run( 'npm', [ 'run', 'build' ], blockEditorAppDir, 'block-editor npm run build' );

if ( ! existsSync( join( blockEditorAssetsDir, '.vite', 'manifest.json' ) ) ) {
	console.error(
		'[071-now] block-editor build produced no manifest at ' +
			'src/block-editor/assets/.vite/manifest.json'
	);
	process.exit( 1 );
}

// Fresh snapshot of the WordPress 0.71 source.
//
//     The block editor's build inputs -- the React source, its
//     node_modules and the Vite config -- live in tools/block-editor/,
//     outside src/, so the snapshot of src/ naturally excludes them.
//     Only src/block-editor/assets/, the build OUTPUT produced just
//     above, is under src/ and belongs in the overlay (editor.php loads
//     it).
rmSync( wpDir, { recursive: true, force: true } );
mkdirSync( wpDir, { recursive: true } );
cpSync( srcDir, wpDir, { recursive: true } );

// src/b2config.php is git-ignored and generated by `071-env start`; on a
//     fresh clone it does not exist, so the snapshot above would omit it
//     and the in-browser blog could not boot. Fall back to the committed
//     src/b2config-sample.php so the playground is self-sufficient -- it
//     uses the SQLite-backed wpdb, so the sample's MySQL credentials are
//     irrelevant and only the file's presence matters.
const overlayConfig = join( wpDir, 'b2config.php' );
if ( ! existsSync( overlayConfig ) ) {
	copyFileSync( join( srcDir, 'b2config-sample.php' ), overlayConfig );
}

// The 071-now database layer files, copied into b2-include/ so the
//     in-browser blog and the boot shim can reach them via the virtual
//     filesystem. wp-db.php replaces 0.71's mysqli-based file; the
//     others sit alongside it with a 071-now- prefix to avoid clashing
//     with any future 0.71 file name.
//       db source              -> in-browser path
const overlayFiles = [
	[ 'wp-db.php', 'wp-db.php' ],
	[ 'sql-translator.php', '071-now-sql-translator.php' ],
	[ 'seed.php', '071-now-seed.php' ],
	[ 'boot.php', '071-now-boot.php' ],
	[ 'mysqli-compat.php', '071-now-mysqli-compat.php' ],
];

for ( const [ from, to ] of overlayFiles ) {
	copyFileSync( join( dbDir, from ), join( wpDir, 'b2-include', to ) );
}

// Resolve the direct mysqli_*( $wpdb->dbh, ... ) call sites.
//
//     A few WordPress 0.71 functions bypass the wpdb methods and call
//     the procedural mysqli_* built-ins directly on $wpdb->dbh, then
//     walk the result with mysqli_fetch_object() / mysqli_fetch_array()
//     / mysqli_fetch_row() / mysqli_num_rows() and read errors with
//     mysqli_error() / mysqli_errno(). Under the 071-now SQLite-backed
//     wpdb, $wpdb->dbh is a PDO -- not a mysqli handle -- so those calls
//     would fatal. The mysqli extension is compiled into php-wasm, so
//     the built-ins cannot be redeclared in userland; the call sites
//     are rewritten instead, to the 071-now mysqli compat helpers (see
//     tools/playground/db/mysqli-compat.php).
//
//     The rewrite runs only on the in-browser copy under
//     tools/playground/wp/; src/ is never touched. It is applied to
//     every file that issues a query on $wpdb->dbh -- enumerated from
//     0.71's source -- so no $wpdb->dbh path can fatal on the PDO
//     handle. b2register.php is deliberately absent: it opens its own
//     mysqli connection ($id), not $wpdb->dbh, and is not part of the
//     SQLite-backed blog.
const mysqliRewriteTargets = [
	'b2-include/b2functions.php',
	'b2-include/b2template.functions.php',
	'wp-admin/b2header.php',
	'wp-admin/b2sidebar.php',
	'wp-admin/b2edit.showposts.php',
	'wp-admin/b2categories.php',
	'wp-admin/linkcategories.php',
	'wp-admin/b2options.php',
	'wp-admin/b2profile.php',
	'wp-admin/linkmanager.php',
	'wp-admin/wp-install.php',
	'wp-admin/b2-2-wp.php',
];

/**
 * Rewrite the direct mysqli_* call sites in one file's text to the
 *     071-now mysqli compat helpers.
 * @param {string} php The PHP source of an affected file.
 * @return {string} The source with the mysqli_* sites rewritten.
 */
function rewriteMysqliCallSites( php ) {
	return (
		php
			// mysqli_query( $wpdb->dbh, X ) -> wp071_db_query( X ).
			//     A leading @ (error suppression) is preserved. Only the
			//     "$wpdb->dbh," first argument is consumed; X and the
			//     closing paren are left intact.
			.replace(
				/(@?)mysqli_query\(\s*\$wpdb->dbh\s*,\s*/g,
				'$1wp071_db_query( '
			)
			// mysqli_error() / mysqli_errno() on the connection handle
			//     -> wp071_db_error(). 0.71 passes either $wpdb->dbh or a
			//     parameter that holds it (linkmanager.php's $dbh).
			.replace(
				/mysqli_err(?:or|no)\(\s*\$[\w>-]+\s*\)/g,
				'wp071_db_error()'
			)
			// The result-walking built-ins -> the cursor helpers. In
			//     these files every such call walks a $wpdb->dbh result.
			.replace( /mysqli_fetch_object\(/g, 'wp071_db_fetch_object(' )
			.replace( /mysqli_fetch_array\(/g, 'wp071_db_fetch_array(' )
			.replace( /mysqli_fetch_row\(/g, 'wp071_db_fetch_row(' )
			.replace( /mysqli_num_rows\(/g, 'wp071_db_num_rows(' )
	);
}

for ( const relativePath of mysqliRewriteTargets ) {
	const filePath = join( wpDir, relativePath );
	if ( ! existsSync( filePath ) ) {
		console.error( `[071-now] mysqli rewrite target missing: ${ relativePath }` );
		process.exit( 1 );
	}
	const original = readFileSync( filePath, 'utf8' );
	const rewritten = rewriteMysqliCallSites( original );
	if ( rewritten !== original ) {
		writeFileSync( filePath, rewritten );
	}
	// A target that still mentions mysqli_ on $wpdb->dbh would fatal
	//     in php-wasm; fail the build so a regression is caught here.
	if ( /mysqli_\w+\(\s*\$wpdb->dbh/.test( rewritten ) ) {
		console.error(
			`[071-now] unrewritten mysqli_*( $wpdb->dbh ) call in ${ relativePath }`
		);
		process.exit( 1 );
	}
}

// WordPress 0.71's front page (src/index.php) links the block-library
//     front-end stylesheet at block-editor/assets/block-library.css, and
//     src/block-editor/api/editor.php loads the block-editor bundle from
//     block-editor/assets/. Both files are build artifacts of the
//     block-editor app, produced by the `npm run build` run above into
//     src/block-editor/assets/ and carried into the overlay by the
//     snapshot. Earlier 071-now builds wrote an empty block-library.css
//     placeholder here because the block editor was a later step; now the
//     real bundle is in place, so only assert it -- a missing file would
//     mean the block-editor build silently produced nothing.
const blockLibraryCss = join(
	wpDir,
	'block-editor',
	'assets',
	'block-library.css'
);
const blockEditorManifest = join(
	wpDir,
	'block-editor',
	'assets',
	'.vite',
	'manifest.json'
);
for ( const required of [ blockLibraryCss, blockEditorManifest ] ) {
	if ( ! existsSync( required ) ) {
		console.error(
			`[071-now] block-editor asset missing from the overlay: ${ required }`
		);
		process.exit( 1 );
	}
}

// Relocate the Vite manifest out of the dot-directory and point the
//     overlay's editor.php at the new location.
//
//     Vite writes its build manifest to block-editor/assets/.vite/
//     manifest.json, and src/block-editor/api/editor.php reads it from
//     there. But the playground writes the whole wp/ tree into the
//     php-wasm filesystem via an import.meta.glob of wp/ in
//     src/wp-files.js, and Vite's import.meta.glob does NOT match files
//     inside a dot-directory -- so .vite/manifest.json would never reach
//     the in-browser blog and editor.php would fall back to its "bundle
//     not built" page even though the bundle is right there.
//
//     The manifest is copied to a sibling non-dot path
//     (block-editor/assets/vite-manifest.json), which the glob does pick
//     up, and the overlay's editor.php is rewritten to read that path.
//     This is the same overlay-only patching as the mysqli rewrite
//     above: the change touches tools/playground/wp/ only -- src/ and the
//     block editor's own assets/ are left exactly as built.
const flatManifest = join(
	wpDir,
	'block-editor',
	'assets',
	'vite-manifest.json'
);
copyFileSync( blockEditorManifest, flatManifest );

const editorPhpPath = join( wpDir, 'block-editor', 'api', 'editor.php' );
const editorPhp = readFileSync( editorPhpPath, 'utf8' );
const patchedEditorPhp = editorPhp.replaceAll(
	'/.vite/manifest.json',
	'/vite-manifest.json'
);
if ( patchedEditorPhp === editorPhp ) {
	console.error(
		'[071-now] editor.php had no .vite/manifest.json reference to rewrite'
	);
	process.exit( 1 );
}
writeFileSync( editorPhpPath, patchedEditorPhp );

console.log( '[071-now] overlay built at tools/playground/wp/' );
console.log( '[071-now]   b2-include/wp-db.php                   <- SQLite-backed wpdb' );
console.log( '[071-now]   b2-include/071-now-sql-translator.php  <- MySQL->SQLite translator' );
console.log( '[071-now]   b2-include/071-now-seed.php            <- database seed' );
console.log( '[071-now]   b2-include/071-now-boot.php            <- auto_prepend boot shim' );
console.log( '[071-now]   b2-include/071-now-mysqli-compat.php   <- mysqli compat helpers' );
console.log(
	`[071-now]   ${ mysqliRewriteTargets.length } files rewritten      <- direct mysqli_*( $wpdb->dbh ) call sites`
);
console.log( '[071-now]   block-editor/assets/                   <- built block-editor bundle + Vite manifest' );
console.log( '[071-now]   block-editor/api/editor.php            <- manifest path rewritten off the .vite/ dot-directory' );
