/*
 * Generate src/b2config.php from src/b2config-sample.php for 071-env.
 *
 *     b2config.php holds environment-specific configuration (database
 *     credentials, blog settings). It is git-ignored; the committed
 *     src/b2config-sample.php is its template. On `071-env start` the
 *     real file is generated from the sample, with the `wpConfig` object
 *     of `.071-env.json` applied as per-environment overrides.
 *
 *     `renderB2Config` is pure: sample text + overrides -> generated
 *     text. `writeB2Config` is the thin impure boundary that reads the
 *     sample and writes the result. The generated file is git-ignored.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { repoRoot } from './paths.mjs';

/** The committed template, tracked in git. */
export const sampleConfigFile = join( repoRoot, 'src', 'b2config-sample.php' );

/** The generated file, git-ignored, served to the web container. */
export const generatedConfigFile = join( repoRoot, 'src', 'b2config.php' );

/**
 * The header inserted right after the opening `<?php`, marking the file
 *     as generated so a developer who opens it knows not to edit it.
 */
const GENERATED_HEADER =
	'// Generated by 071-env from src/b2config-sample.php on `071-env start`.\n' +
	'//     Do not edit -- it is git-ignored and regenerated. Change the\n' +
	'//     defaults in src/b2config-sample.php, or set per-environment\n' +
	'//     values in the `wpConfig` object of .071-env.json.';

/**
 * Escape a string for literal use inside a RegExp.
 * @param {string} text The string.
 * @returns {string} the escaped string.
 */
function escapeForRegExp( text ) {
	return text.replace( /[.*+?^${}()|[\]\\]/g, '\\$&' );
}

/**
 * Render a JavaScript value as a PHP literal.
 * @param {string|number|boolean} value The override value.
 * @returns {string} the PHP literal.
 */
function phpLiteral( value ) {
	if ( typeof value === 'number' || typeof value === 'boolean' ) {
		return String( value );
	}
	// A single-quoted PHP string: only \ and ' are special inside it.
	return `'${ String( value ).replace( /\\/g, '\\\\' ).replace( /'/g, "\\'" ) }'`;
}

/**
 * Apply one override to the b2config text. The key names a b2config
 *     variable (`$key = ...;`) or a defined constant
 *     (`define( 'key', ... )`); the first matching assignment's value is
 *     replaced. Throws when the key matches neither -- a typo, or an
 *     array / derived value that cannot be overridden this way.
 * @param {string} text  The b2config text being built.
 * @param {string} key   The variable / constant name.
 * @param {string} value The PHP literal to assign.
 * @returns {string} the text with the override applied.
 * @throws {Error} when the key matches no assignment.
 */
function applyOverride( text, key, value ) {
	const name = escapeForRegExp( key );

	// A simple `$key = <rhs>;` assignment; the rhs holds no ';'. Any
	//     trailing `// comment` after the ';' is left untouched.
	const varPattern = new RegExp(
		`^([ \\t]*\\$${ name }[ \\t]*=[ \\t]*)[^;\\n]*;`,
		'm'
	);
	if ( varPattern.test( text ) ) {
		return text.replace( varPattern, `$1${ value };` );
	}

	// A `define( 'KEY', <rhs> )` constant -- the DB_* credentials.
	const definePattern = new RegExp(
		`(\\bdefine\\([ \\t]*'${ name }'[ \\t]*,[ \\t]*).*?([ \\t]*\\))`
	);
	if ( definePattern.test( text ) ) {
		return text.replace( definePattern, `$1${ value }$2` );
	}

	throw new Error(
		`wpConfig: no $${ key } assignment or define( '${ key }', ... ) ` +
			'found in b2config-sample.php.'
	);
}

/**
 * Render the b2config.php text from the sample and the wpConfig
 *     overrides. With an empty `wpConfig` the result is the sample plus
 *     the generated-by header -- functionally identical to the sample.
 * @param {string}            sampleText The src/b2config-sample.php text.
 * @param {Record<string,*>}  wpConfig   The `wpConfig` overrides.
 * @returns {string} the generated b2config.php text.
 * @throws {Error} when an override key matches no assignment.
 */
export function renderB2Config( sampleText, wpConfig = {} ) {
	// Mark the file as generated, right after the opening `<?php`.
	let text = sampleText.replace(
		/^<\?php\n/,
		`<?php\n${ GENERATED_HEADER }\n\n`
	);

	for ( const [ key, value ] of Object.entries( wpConfig || {} ) ) {
		text = applyOverride( text, key, phpLiteral( value ) );
	}

	return text;
}

/**
 * Read src/b2config-sample.php, apply the wpConfig overrides, and write
 *     src/b2config.php.
 * @param {Record<string,*>} wpConfig The `wpConfig` overrides ({} for none).
 * @throws {Error} when the sample is missing or an override key is unknown.
 */
export function writeB2Config( wpConfig = {} ) {
	const sample = readFileSync( sampleConfigFile, 'utf8' );
	writeFileSync( generatedConfigFile, renderB2Config( sample, wpConfig ) );
}
