/*
 * Runtime Compose-override generation for the `mappings` config field.
 *
 *     `.071-env.json`'s `mappings` field maps a container path to a host path
 *     -- extra read-write bind mounts for the `web` container, the analogue
 *     of wp-env's `mappings`. Compose appends `volumes` lists cleanly across
 *     `-f` files, so the right mechanism is a generated override file that
 *     071-env passes in addition to `tools/env/docker-compose.yml` and
 *     `tools/env/docker-compose.071.yml`.
 *
 *     `renderMappingsOverride` is pure: it turns the `mappings` object into
 *     Compose YAML text. `writeMappingsOverride` is the thin impure boundary
 *     that writes that text to disk (and removes a stale file when there are
 *     no mappings). The generated file is git-ignored.
 */

import { writeFileSync, existsSync, rmSync } from 'node:fs';
import { mappingsOverrideFile } from './paths.mjs';

/**
 * Render the runtime Compose override that adds the configured `mappings`
 *     as extra `volumes` on the `web` service. Returns `null` when there are
 *     no mappings -- the caller then writes no file and passes no extra `-f`.
 *
 *     Each mapping is a read-write bind mount `host:container`. Host paths are
 *     resolved relative to the repository root by Compose itself (the
 *     generated file lives at the repository root). The values are wrapped in
 *     double quotes so paths with spaces survive YAML parsing.
 *
 * @param {Record<string,string>} mappings Container path -> host path.
 * @returns {string|null} the YAML text, or null when there are no mappings.
 */
export function renderMappingsOverride( mappings ) {
	const entries = Object.entries( mappings || {} );
	if ( entries.length === 0 ) {
		return null;
	}

	const lines = [
		'# Generated by 071-env from the `mappings` field of .071-env.json.',
		'# Do not edit by hand -- it is regenerated on every `071-env start`',
		'# and is git-ignored. It adds extra read-write bind mounts to the',
		'# `web` service; Compose appends `volumes` across -f files.',
		'services:',
		'  web:',
		'    volumes:',
	];

	// Sort by container path so the generated file is deterministic.
	for ( const [ containerPath, hostPath ] of entries.sort( ( a, b ) => a[ 0 ].localeCompare( b[ 0 ] ) ) ) {
		lines.push( `      - "${ hostPath }:${ containerPath }"` );
	}

	return `${ lines.join( '\n' ) }\n`;
}

/**
 * Write (or remove) the runtime mappings override file. When `mappings`
 *     has entries the file is written and its path returned; when `mappings`
 *     is empty any stale file is deleted and `null` is returned. The caller
 *     adds the returned path as an extra `-f` only when it is non-null.
 * @param {Record<string,string>} mappings Container path -> host path.
 * @returns {string|null} the absolute path of the written file, or null.
 */
export function writeMappingsOverride( mappings ) {
	const yaml = renderMappingsOverride( mappings );

	if ( yaml === null ) {
		// No mappings -- remove a file left over from a previous run so a
		//     stale mount cannot linger.
		if ( existsSync( mappingsOverrideFile ) ) {
			rmSync( mappingsOverrideFile );
		}
		return null;
	}

	writeFileSync( mappingsOverrideFile, yaml );
	return mappingsOverrideFile;
}
