/*
 * EN: Runtime Compose-override generation for the `mappings` config field.
 *
 *     `.071-env.json`'s `mappings` field maps a container path to a host path
 *     -- extra read-write bind mounts for the `web` container, the analogue
 *     of wp-env's `mappings`. Compose appends `volumes` lists cleanly across
 *     `-f` files, so the right mechanism is a generated override file that
 *     071-env passes in addition to `tools/env/docker-compose.yml` and
 *     `tools/env/docker-compose.071.yml`.
 *
 *     `renderMappingsOverride` is pure: it turns the `mappings` object into
 *     Compose YAML text. `writeMappingsOverride` is the thin impure boundary
 *     that writes that text to disk (and removes a stale file when there are
 *     no mappings). The generated file is git-ignored.
 *
 * JA: `mappings` 設定フィールドのための実行時 Compose オーバーライド生成。
 *
 *     `.071-env.json` の `mappings` フィールドはコンテナパスをホストパスへ
 *     対応付ける -- `web` コンテナ向けの追加の読み書きバインドマウントで
 *     あり、wp-env の `mappings` の相当物である。Compose は `-f` ファイル
 *     間で `volumes` のリストをきれいに追記するため、正しい仕組みは、
 *     071-env が `tools/env/docker-compose.yml` と
 *     `tools/env/docker-compose.071.yml` に加えて渡す、生成された上書き
 *     ファイルである。
 *
 *     `renderMappingsOverride` は純粋関数で、`mappings` オブジェクトを
 *     Compose の YAML テキストへ変換する。`writeMappingsOverride` はその
 *     テキストをディスクへ書く (マッピングが無いときは古いファイルを削除
 *     する) 薄い非純粋な境界である。生成されるファイルは git 管理外である。
 */

import { writeFileSync, existsSync, rmSync } from 'node:fs';
import { mappingsOverrideFile } from './paths.mjs';

/**
 * EN: Render the runtime Compose override that adds the configured `mappings`
 *     as extra `volumes` on the `web` service. Returns `null` when there are
 *     no mappings -- the caller then writes no file and passes no extra `-f`.
 *
 *     Each mapping is a read-write bind mount `host:container`. Host paths are
 *     resolved relative to the repository root by Compose itself (the
 *     generated file lives at the repository root). The values are wrapped in
 *     double quotes so paths with spaces survive YAML parsing.
 *
 * JA: 設定された `mappings` を `web` サービスの追加 `volumes` として加える
 *     実行時 Compose オーバーライドを描画する。マッピングが無い場合は
 *     `null` を返す -- 呼び出し側はファイルを書かず、追加の `-f` も渡さない。
 *
 *     各マッピングは読み書きのバインドマウント `host:container` である。
 *     ホストパスは Compose 自身がリポジトリルートからの相対で解決する
 *     (生成ファイルはリポジトリルートに置かれる)。値は二重引用符で囲み、
 *     空白を含むパスが YAML 解析を通るようにする。
 *
 * @param {Record<string,string>} mappings Container path -> host path.
 * @returns {string|null} the YAML text, or null when there are no mappings.
 */
export function renderMappingsOverride( mappings ) {
	const entries = Object.entries( mappings || {} );
	if ( entries.length === 0 ) {
		return null;
	}

	const lines = [
		'# EN: Generated by 071-env from the `mappings` field of .071-env.json.',
		'#     Do not edit by hand -- it is regenerated on every `071-env start`',
		'#     and is git-ignored. It adds extra read-write bind mounts to the',
		'#     `web` service; Compose appends `volumes` across -f files.',
		'# JA: .071-env.json の `mappings` フィールドから 071-env が生成する。',
		'#     手で編集しないこと -- `071-env start` のたびに再生成され、git',
		'#     管理外である。`web` サービスに追加の読み書きバインドマウントを',
		'#     加える。Compose は -f ファイル間で `volumes` を追記する。',
		'services:',
		'  web:',
		'    volumes:',
	];

	// EN: Sort by container path so the generated file is deterministic.
	// JA: 生成ファイルが決定的になるよう、コンテナパスでソートする。
	for ( const [ containerPath, hostPath ] of entries.sort( ( a, b ) => a[ 0 ].localeCompare( b[ 0 ] ) ) ) {
		lines.push( `      - "${ hostPath }:${ containerPath }"` );
	}

	return `${ lines.join( '\n' ) }\n`;
}

/**
 * EN: Write (or remove) the runtime mappings override file. When `mappings`
 *     has entries the file is written and its path returned; when `mappings`
 *     is empty any stale file is deleted and `null` is returned. The caller
 *     adds the returned path as an extra `-f` only when it is non-null.
 * JA: 実行時マッピングオーバーライドファイルを書く (または削除する)。
 *     `mappings` にエントリがあればファイルを書きそのパスを返す。`mappings`
 *     が空なら古いファイルを削除し `null` を返す。呼び出し側は返り値が
 *     非 null のときだけ、そのパスを追加の `-f` として加える。
 *
 * @param {Record<string,string>} mappings Container path -> host path.
 * @returns {string|null} the absolute path of the written file, or null.
 */
export function writeMappingsOverride( mappings ) {
	const yaml = renderMappingsOverride( mappings );

	if ( yaml === null ) {
		// EN: No mappings -- remove a file left over from a previous run so a
		//     stale mount cannot linger.
		// JA: マッピング無し -- 前回の実行で残ったファイルを削除し、古い
		//     マウントが残らないようにする。
		if ( existsSync( mappingsOverrideFile ) ) {
			rmSync( mappingsOverrideFile );
		}
		return null;
	}

	writeFileSync( mappingsOverrideFile, yaml );
	return mappingsOverrideFile;
}
