/*
 * Unit tests for tools/env/src/b2config.mjs -- rendering b2config.php
 *     from the sample with `wpConfig` overrides applied. `renderB2Config`
 *     is pure (sample text + overrides -> text), so it is tested
 *     directly; the filesystem-touching `writeB2Config` is not exercised
 *     here.
 */

import test from 'node:test';
import assert from 'node:assert/strict';

import { renderB2Config } from '../src/b2config.mjs';

// A small stand-in for src/b2config-sample.php: a $var with a trailing
//     comment, a plain $var, a numeric $var, and a guarded define().
const SAMPLE = [
	'<?php',
	"$siteurl  = 'http://localhost:8080'; // the blog URL",
	"$blogname = 'my weblog';",
	'$start_of_week = 1;',
	"if ( ! defined( 'DB_NAME' ) ) {",
	"\tdefine( 'DB_NAME', 'b2' );",
	'}',
	'',
].join( '\n' );

test( 'renderB2Config: with no overrides keeps every assignment and adds the header', () => {
	const out = renderB2Config( SAMPLE, {} );
	assert.match( out, /Generated by 071-env/ );
	assert.match( out, /\$blogname = 'my weblog';/ );
	assert.match( out, /\$siteurl {2}= 'http:\/\/localhost:8080';/ );
	assert.match( out, /define\( 'DB_NAME', 'b2' \)/ );
} );

test( 'renderB2Config: overrides a $var assignment', () => {
	const out = renderB2Config( SAMPLE, { blogname: 'a new blog' } );
	assert.match( out, /\$blogname = 'a new blog';/ );
	assert.doesNotMatch( out, /my weblog/ );
} );

test( 'renderB2Config: a $var override keeps the trailing comment', () => {
	const out = renderB2Config( SAMPLE, { siteurl: 'http://example.test' } );
	assert.match(
		out,
		/\$siteurl {2}= 'http:\/\/example\.test'; \/\/ the blog URL/
	);
} );

test( 'renderB2Config: a numeric value is written as a bare literal', () => {
	const out = renderB2Config( SAMPLE, { start_of_week: 0 } );
	assert.match( out, /\$start_of_week = 0;/ );
} );

test( 'renderB2Config: overrides a define() constant', () => {
	const out = renderB2Config( SAMPLE, { DB_NAME: 'wp071' } );
	assert.match( out, /define\( 'DB_NAME', 'wp071' \)/ );
	assert.doesNotMatch( out, /'b2'/ );
} );

test( 'renderB2Config: a single quote in a string value is escaped', () => {
	const out = renderB2Config( SAMPLE, { blogname: "Bob's blog" } );
	assert.match( out, /\$blogname = 'Bob\\'s blog';/ );
} );

test( 'renderB2Config: an unknown key throws', () => {
	assert.throws(
		() => renderB2Config( SAMPLE, { nonesuch: 'x' } ),
		/no \$nonesuch assignment or define/
	);
} );
